### PR TITLE
add an optional property to add custom packets to createClient and createServer

### PR DESCRIPTION
**Pull request by rom1504**
@deathcap I think this should be enough for your forge use cases.

Should customPackets be indexed by version too, so packets only get added for a given version ?

### CODE REVIEW

**Comment by rom1504** [comment]
So it seems greenkeeper got @roblabla test account banned, great.

**Comment by rom1504** [comment]
@deathcap this would also make it possible to override packets for https://github.com/deathcap/minecraft-data/blob/mc17varshort/data/1.7/protocol.json#L1908

**Comment by rom1504** [comment]
That works.

**Comment by roblabla** [comment]
@rom1504 my account wasn't banned. Mojang sent me an email saying they got "suspicious activity" and reset my password :laughing: 

I can put back the same password if you want.

**Pull request merged**
