### PR TITLE
authserver.mojang.com is now sessionserver.mojang.com

### PR DESCRIPTION
**Pull request by Mqrco0Wurstelli**
I have never done a pull request on github lmao
by the way authserver.mojang.com has been changed to sessionserver.mojang.com

### CODE REVIEW

**Comment by extremeheat** [comment]
Can you elaborate on the PR? 

> authserver.mojang.com has been changed to sessionserver.mojang.com

Where are you getting that information?

**Comment by Mqrco0Wurstelli** [comment]
> Can you elaborate on the PR? 
> 
> > authserver.mojang.com has been changed to sessionserver.mojang.com
> 
> Where are you getting that information?

Honestly just searched online
My proxy didnt work anymore, set the authserver to sessionserver.mojang.com and it now works.
(btw the the domani authserver.mojang.com doesnt even exist anymore)

**Comment by extremeheat** [comment]
The auth server doesn’t exist because mojang auth doesn’t exist anymore. It has nothing to do with a rename

**Comment by Mqrco0Wurstelli** [comment]
oh then mb :(

**Pull request closed without merging**
