### PR TITLE
Remove asserts from non-test code

### PR DESCRIPTION
**Pull request by wtfaremyinitials**
#61

### CODE REVIEW

**Comment by wtfaremyinitials** [comment]
Odd...

The tests pass on my machine.

**Comment by roblabla** [comment]
1. This should be using `new Error()` instead of throwing strings. Otherwise, we lose the stacktrace information, and that sucks.
2. The real problem behind #61 is that throwing in protocol.js does not trigger an "error" event in mineflayer, but instead throws an uncatchable error outside of user code. This is obviously unacceptable for a library, especially for creating servers.

**Comment by rom1504** [comment]
There are still some assert in the current code, this should be fixed.

**Comment by roblabla** [comment]
Asserts are normal since we're now using throws instead of `return { error }`. What needs to be fixed is, subclassing errors in a way that they make sense.

**Comment by rom1504** [comment]
@roblabla asserts emit exception ?

**Comment by roblabla** [comment]
@rom1504 asserts throw an Error, which we catch higher up the stack and transform into an emit error. That's what we want. We just want to modify those asserts so they use custom error classes instead.

**Pull request closed without merging**
