### PR TITLE
add protocolValidation field to server and client options

### PR DESCRIPTION
**Pull request by RichardDorian**
It's a better way of just completly disabling the validator. Hope this will be merged :D

### CODE REVIEW

**Comment by rom1504** [comment]
You added it only to client options

**Comment by RichardDorian** [comment]
> You added it only to client options

Look at my Discord message, https://discord.com/channels/413438066984747026/413438248342257677/947566301864423465

**Comment by rom1504** [comment]
can you add the option to the doc?

**Comment by rom1504** [comment]
and pick a name related with what the option is doing, ie enable/disable validation for plugin channels

**Comment by RichardDorian** [comment]
Sure! I'll do it tomorrow 😉

**Comment by RichardDorian** [comment]
Done :D

**Comment by rom1504** [comment]
no not yet, you still need to change the name of `protocolValidation` as it doesn't represent what it is doing
the name should include the fact it's only for plugin channels

**Pull request merged**
