### PR TITLE
Don't write out packets if connection is ended

### PR DESCRIPTION
**Pull request by pcfreak30**
Don't write out packets if connection is ended, and mark as ended on end method

### CODE REVIEW

**Comment by wtfaremyinitials** [comment]
Looks good to me. @roblabla?

**Comment by roblabla** [comment]
Thank you for your contribution. This won't quite work though : you'll want to remove the ```ended``` variable from the [setSocket function](https://github.com/pcfreak30/node-minecraft-protocol/blob/master/lib/client.js#L118), and change every occurrence of that variable to ```self.ended```.

**Comment by pcfreak30** [comment]
From what I could tell, the "end" event is never called, so ended is never set from my debugging. I kept getting write after end errors when calling end() on the bot library. This prevented outbound writes once end is called and set before its actually closed.

**Comment by roblabla** [comment]
end event is called whenever the TCP connection is lost, whether it is because the server shut it down, or because you lost your internet connection. So outbound writes won't work past that point either. Calling socket.end() will not call the end event, I guess, but that doesn't mean the event should still be ignored. 

Besides, the 'error' event also calls endSocket, and you definitly don't want writes after a TCP error ^^.

**Pull request closed without merging**
