### PR TITLE
Add connect to types

### PR DESCRIPTION
**Pull request by ShayBox**
Add missing connect function to typings for Client
<https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client.js#L222>

### CODE REVIEW

**Comment by ShayBox** [comment]
I would also like to point out the typings export "States" but the actual code exports "states", whichever one should be changed I don't know.

**Comment by rom1504** [comment]
the typing should be changed probably

**Comment by ShayBox** [comment]
Documentation is the clear downfall of this library,
- Typings aren't complete or updated consistently
- The manually written documentation markdown isn't updated consistently
- And there's no other form of documentation like (ex. jsdoc) that is

I think there needs to be a big focus on getting some form of documentation on this project complete, and kept up to date with the actual source, whether that's typescript definitions or jsdoc comments.

There's also a few inconsistent styling choices, like in ServerOptions, all of the options are camelCase except for "online-mode", or having both callbacks (es5) and events (es6).

**Comment by rom1504** [comment]
I don't think jsdoc would help at all here.  Especially since there have
been basically no change in the API for years.
There are very few things that should be used from the library, basically
only createClient and createServer.
There are lot of examples for all the possible use cases.

If you're interested in working on docs, I think something that would be
useful is a hand written tutorial on the basic js concept here (callback
async), some basic network explanation (tcp, packets, serialization), and
what this lib can be used for.
The majority of people that get confused here are people who miss big area
of knowledge in some of these things.

**Comment by ShayBox** [comment]
I mentioned jsdoc as an example, I thought it would likely be updated more being comments visible from the code.

There's a lot about this project I can't fix in a pr, the mix of ES5 and ES6 mainly, but I fixed some small things here <https://github.com/ShayBox/node-minecraft-protocol/commit/b327f93bcf38df77b5e436a6059c78ab47612c41>

**Comment by rom1504** [comment]
Yeah what I think wouldn't help is comment in code and doc generated from
that. You lose the coherence when doing that which is probably the most
important thing to understand for this lib

**Pull request merged**
