### PR TITLE
Update prismarine-auth usage

### PR DESCRIPTION
**Pull request by extremeheat**
* add new `deviceType` parameter
* implement changes in https://github.com/PrismarineJS/prismarine-auth/pull/21

### CODE REVIEW

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-auth/pull/21 is merged, can you do a release there ?

**Comment by rom1504** [comment]
and fix lint

**Comment by extremeheat** [comment]
Should be fixed

**Comment by rom1504** [comment]
don't you need a release for https://github.com/PrismarineJS/prismarine-auth/commit/457b00f2f0ca6359c75d76fdc13e3137cc6adc81 as well ?

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
