### PR TITLE
1.20

### PR DESCRIPTION
**Pull request by PondWader**
After https://github.com/PrismarineJS/minecraft-data/pull/721 
Requires #1231 for tests to pass (will merge in to my branch once merged here)

### CODE REVIEW

**Comment by rom1504** [comment]
this is failing. do you plan to look into it ?

**Comment by PondWader** [comment]
> this is failing. do you plan to look into it ?

"Requires https://github.com/PrismarineJS/node-minecraft-protocol/pull/1231 for tests to pass (will merge in to my branch once merged here)"

**Comment by PondWader** [comment]
There we go

**Comment by rom1504** [comment]
Unrelated with this PR but I notice the packet cycle test have stopped being updated since 1.16
I'll open an issue so we fix that

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/1233

**Pull request merged**
