### PR TITLE
Fix missing readable-stream types

### PR DESCRIPTION
**Pull request by IceTank**
This should fix an issue with typescript for people that do not have readable-stream installed globally

### CODE REVIEW

**Comment by jojomatik** [comment]
This fix doesn't work for me as well unfortunately.

`devDependencies` are not considered for projects using this library.

I could however add `"@types/readable-stream": "^2.3.13",` as a dev dependency of my project, but that doesn't sound quite right to me. I never had to install some the types of a dependencies dependency before.

I'm not sure how, but I think it should be somehow possible to include that type.

**Comment by IceTank** [comment]
I think adding it to normal dependencies should be fine

**Comment by jojomatik** [comment]
Could you create a new release @rom1504, so that I can use this in the production version of my project?

**Comment by rom1504** [comment]
You can make a release PR, then i just need to press merge

**Comment by jojomatik** [comment]
> You can make a release PR, then i just need to press merge

#988

**Pull request merged**
