### PR TITLE
Mc 1.19

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rob9315** [comment]
1.19 **.0** in ci?

**Comment by rob9315** [comment]
nice ci fail on 1.19
`Uncaught Error: listen EADDRINUSE: address already in use :::40065`

**Comment by rom1504** [comment]
no that's just further tests failing due to a previous one having failed

**Comment by rom1504** [comment]
```
PartialReadError: Read error for undefined : Missing characters in string, found size is 26961 expected size was 28021
    at new ExtendableError (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/utils.js:70:5)
    at Object.shortString (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:70:15)
    at Object.readPString [as nbtTagName] (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:30:35)
    at nbt (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:150:61)
    at CompiledProtodef.read (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:70:12)
    at Object.readNbt [as nbt] (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/src/datatypes/minecraft.js:47:20)
    at eval (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1199:33)
    at Object.packet_login (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1204:9)
    at eval (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2[281](https://github.com/PrismarineJS/node-minecraft-protocol/runs/7425731280?check_suite_focus=true#step:6:282):50)
    at packet (eval at compile (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2353:9)
    at CompiledProtodef.read (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/compiler.js:111:29)
    at FullPacketParser.parsePacketBuffer (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/serializer.js:68:23)
    at FullPacketParser._transform (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/src/serializer.js:74:21)
    at FullPacketParser.Transform._read (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at FullPacketParser.Writable.write (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Decompressor.ondata (/home/runner/work/node-minecraft-protocol/node-minecraft-protocol/node_modules/readable-stream/lib/internal/streams/readable.js:693:22)
    at Decompressor.emit (events.js:400:28)
```
this is the actual error

it means packet def is wrong.

packet_login nbt looks like what you fixed

**Comment by rom1504** [comment]
rerunning with released mcdata

**Comment by rob9315** [comment]
1.12.2 is failing?
https://github.com/PrismarineJS/node-minecraft-protocol/runs/7427080235?check_suite_focus=true

**Comment by nickelpro** [comment]
That looks like a VM blip, server tried to open a socket and the OS reported the socket already in use

**Comment by rob9315** [comment]
1.19 failed because of declare_commands, which is expected

**Comment by rob9315** [comment]
fix [here](https://github.com/PrismarineJS/minecraft-data/pull/596)

**Comment by rob9315** [comment]
wait, why is it set up that way?

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/packetTest.js

Fixing that code to let it generate values for dedicated types would be ideal

**Comment by rob9315** [comment]
ok, sure.
btw looking at that, the uuid example is in an invalid format:
`00112233-4455-6677-8899-aabbccddeeff`
image

**Comment by rom1504** [comment]
Moved to other PR

**Pull request closed without merging**
