### PR TITLE
transform play numerical ids to names

### PR DESCRIPTION
**Pull request by rom1504**
* start working on #232 
* remove entity metadata test values (that should probably be in a datatypes/ test or something) to support cross version
* improve error handling a bit in serializer.js

### CODE REVIEW

**Comment by roblabla** [comment]
Is this ready to merge ?

**Comment by rom1504** [comment]
yeah

**Comment by roblabla** [comment]
With this merged, we'll want to stop emitting packets by ID and [state;id] I think.

**Comment by rom1504** [comment]
@roblabla this PR changes the numerical ids into names for the PLAY state, but I didn't change anything for the other states, would using the name for the other states "just work" ? (I think there was some name conflict)

(example there : https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createClient.js#L49 )

**Comment by roblabla** [comment]
There shouldn't be any name conflict (we make sure of that in packets.js). It should "just work". The only trouble is, I can't find where we're emitting the packets by [state;id] ._.

**Comment by roblabla** [comment]
Right, we don't emit packetIds or [state; packetIds]. Instead, we overload on to transform it into packetName : https://github.com/PrismarineJS/node-minecraft-protocol/blob/e3b435af1b4a3fad192d9534fca2cac466c520eb/src/client.js#L70

**Pull request merged**
