### PR TITLE
chore(runtime): use LTS V18

### PR DESCRIPTION
**Pull request by AugustinMauroy**
V14 will become deprecated.

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
If you go on docs we use `node:`
`node:` mean it's an internal module.

and new internal module can only found using `node:` example `test`

**Comment by rom1504** [comment]
ok, but why?

when will nodejs reverse this?

**Comment by AugustinMauroy** [comment]
Now `test` module is only available with `node:test`

**Comment by rom1504** [comment]
yeah I read https://stateful.com/blog/node-18-prefix-only-modules

I disagree, it's a bad change, it makes all future nodejs code not work with previous versions, for no strong reason.

Let's not use these prefixes

**Comment by AugustinMauroy** [comment]
If you want the project to remain "healthy" you have to stay with LTS, so in any case the anicien code will be deprecated.

**Comment by rom1504** [comment]
refer to https://github.com/PrismarineJS/prismarine-meta/issues/8 for why

**Pull request merged**
