### PR TITLE
Added multiprotocol example for 1.19.0 - 1.19.3 + Better code in some examples

### PR DESCRIPTION
**Pull request by andriycraft**

### CODE REVIEW

**Comment by andriycraft** [comment]
image

**Comment by andriycraft** [comment]
You should switch from `standardjs` to `prettier`

**Comment by andriycraft** [comment]
@rom1504

**Comment by andriycraft** [comment]
@rom1504

**Comment by rom1504** [comment]
Please say what it is
Looks like like of package.json removed. Why ?

**Comment by andriycraft** [comment]
> Looks like like of package.json removed. Why ? 

Whats the point of containing package json that has no dependencies and basically useless

**Comment by rom1504** [comment]
to keep the same pattern in all examples

also your file new names don't follow the snake case convention

**Comment by faaxz** [comment]
> > Looks like like of package.json removed. Why ?
> 
> Whats the point of containing package json that has no dependencies and basically no usage

Well, actually i kinda agree with you here

**Comment by IceTank** [comment]
Why have the old files been renamed? I don't see a reason why they should be renamed.

**Comment by andriycraft** [comment]
> Why have the old files been renamed? I don't see a reason why they should be renamed.

To follow camelCase file naming

**Comment by rom1504** [comment]
old

**Comment by andriycraft** [comment]
old👍

**Pull request closed without merging**
