### PR TITLE
Pass through http agent option to yggdrasil for proxy support

### PR DESCRIPTION
**Pull request by IdanHo**
To be merged only if and when PrismarineJS/node-yggdrasil#36 is merged.

### CODE REVIEW

**Comment by wvffle** [comment]
Bunp the version when PrismarineJS/node-yggdrasil#36 gets merged and published

**Comment by IdanHo** [comment]
> can you update the proxy example and the doc so people know how to use this ?

i can update the doc, but updating the proxy example would require a package like ProxyAgent (https://www.npmjs.com/package/proxy-agent) in order to actually pass through proxy settings via the http agent field, is that fine?

**Comment by rom1504** [comment]
yes you can add the dependency in the package.json of the example

**Comment by IdanHo** [comment]
done.

**Comment by rom1504** [comment]
@IdanHo I released 1.3.0 of yggdrasil with your changes, can you update dependency in package.json here ?

**Comment by IdanHo** [comment]
done.

**Pull request merged**
