### PR TITLE
[WIP] Add plugin channel API to NMP

### PR DESCRIPTION
**Pull request by deathcap**
Adds the start of an API for "plugin channels" in node-minecraft-protocol

Use cases include:

* https://github.com/PrismarineJS/node-minecraft-protocol/issues/152 Handle official (MC| - prefixed) Custom Payload packets
* https://github.com/PrismarineJS/node-minecraft-protocol/issues/114 Forge Support
 * https://github.com/PrismarineJS/node-minecraft-protocol/pull/326 Forge client support - experimenting building on this API for `FML|HS` in internal PR: https://github.com/deathcap/node-minecraft-protocol/pull/2
* https://github.com/PrismarineJS/mineflayer/issues/361 Plugin channel API in mineflayer
 * [MC|AdvCdm](https://github.com/PrismarineJS/mineflayer/commit/24f24349261c5b5031ff4ec624fef670af3028a5), [MC|Brand](https://github.com/PrismarineJS/mineflayer/issues/253)

To do:

* [ ] Rework to use nodejs streams

### CODE REVIEW

**Comment by deathcap** [comment]
This could be enhanced further (let NMP deserialize the channels it knows about, have a mechanism to register custom codecs, etc.), but I think this basic implementation is good enough to integrate for now, allowing other code to build upon it - including some which may be better in separate modules (https://github.com/PrismarineJS/node-minecraft-protocol/pull/326)

**Comment by deathcap** [comment]
Not sure of the best API design here, does it make sense to have separate incomingPluginChannels and outgoingPluginChannels objects, or would it be cleaner to have only one pluginChannels object, with both incoming and outgoing channel sets?

If so same object could support both receiving (emitted events, `on`) and sending (`write()`), but the client/server can have different plugin channels registered, so I think they should be kept separate to some extent. Open to ideas..

**Comment by roblabla** [comment]
I'm fine with both side them being separate or kept together. They both have their own set of advantages.

The way I envision the API is like so : 

```
var forgeChannel = client.incomingChannel('SOME_CHANNEL_I_OWN');
forgeChannel.on('data', function(data) {
});
```

The first call to "incomingChannel" should result in a "REGISTER" event being sent, the others the same object should be retrieved from a cache.

This has the advantage of being fully compatible with the nodejs stream api. So I can pipe stuff from and to the channel without problems. Meaning if I want to deserialize the data, I can do

```
var forgeChannel = client.incomingChannel('SOME_CHANNEL_I_OWN');
forgeChannel.pipe(new Protocol([{ type: "byte", "name": "data" }]).createStream())
.on('data', function(data) {
  console.log(data.data);
});
```

(Probably not the correct way to create a Protocol stream but nvm that :P)

**Comment by deathcap** [comment]
:+1: for nodejs stream api compatibility

**Comment by deathcap** [comment]
Some notes about registration:

The REGISTER/UNREGISTER packets accept multiple null-delimited channel names, and FML/Forge does send them all at once, so I think supporting multiple simultaneous registrations/unregistrations at the API level may be worthwhile.

On the other hand, it doesn't seem registration has much effect in the software I've tested. FML/Forge lets you send packets on a channel without REGISTER, and it happily proceeds just fine. On our side, packets for non-registered channels are still forwarded, it would be an extra check to drop non-registered channel payloads, not really clear why they added registration/unregistration in the first place (maybe to allocate resources? to advertise the fact that the other side supports some feature? but they'll already ignore unknown channels..)

There's also the complication that built-in `MC|` channels do not need registration. For these reasons, maybe (un)registration should be explicit. Have the API allow listening on arbitrary channels (possibly multiple listeners per channel?), and register/unregister a list of channels as specified.

Anyways, I like the idea of creating channels using nodejs streams. This solves most of the API design problem, since nodejs streams are a standard API other modules can easily hook into. Maybe bidirectional streams, to easily allow sending/receiving on an outgoing/incoming channel of the same name. [stream.Duplex](https://nodejs.org/api/stream.html#stream_class_stream_duplex_1). Or keep them separate `Writable`/`Readable` for simplicity, not too strong of an opinion about either way.

todo: change to use streams and update nmp-forge

**Comment by roblabla** [comment]
Hmm, a Duplex stream might make sense. Then the api would be reduced to a simple call like `client.channel('CHANNEL_NAME`);`, which is pwetty neat.

Concerning the whole registration fiasco, CraftBukkit, IIRC, forces registration, otherwise it will just ignore the packets. I think we should do this by the spec.

As far as registering multiple channels at once, I really don't see much gain in that. The overhead of the channel packet is very very small, we're going from 10 bytes ("REGISTER".length + packetId + len) to 1 byte overhead. Not a huge win in the grand scheme of things, especially since channels are REGISTER'd extremely rarely in the 99.999% case.

**Comment by deathcap** [comment]
I suppose if Forge accepts its channel registration in multiple REGISTER packets, it could be acceptable for the API to not support multiple simultaneous channel registrations. Would need to test to be sure, but it is probably fine. Another quirk in Forge's channel registration is that it registers the "FML" channel twice (it sends `FML|HS\x00FML\x00FML|MP\x00FML\x00FORGE`), probably a bug I but I tried to match the behavior byte-for-byte in nmp-forge, granted maybe unnecessarily

**Comment by roblabla** [comment]
Yeah, that is a bug. And i know multiple register packets work. Used to do
that back when i did mod dev, and it shouldn't have changed since then.

**Comment by deathcap** [comment]
Started to convert to use a Duplex stream, but got stuck on implementing the `_read()` stream method from an event emitter. This looks useful:

https://github.com/substack/emit-stream - turn event emitters into streams and streams into event emitters

but not clear how it interacts with Duplex streams (as it returns a Stream). Having second thoughts about Duplex streams versus separate readable and writables. The WHATWG standard web stream project, which has Node.js developers participating to improve on the streams spec, decided against duplex streams in preference to pairs of streams on each end: https://github.com/whatwg/streams/blob/master/FAQ.md#what-are-the-main-differences-between-these-streams-and-nodejs-streams

> For the concept of something with a writable end and a readable end, we have "duplex streams." Duplex streams are really just containers for a pair of streams, one writable and one readable, stored in the properties writable and readable respectively.

**Comment by roblabla** [comment]
For _read(), what you should do is something like

```js
var readable = new Readable();
readable._read = function() {
  // First, read everything currently in the cache.
  var areWeDone = false;
  while (readable.readStuff.length > 0 && areWeDone) {
    areWeDone = this.push(this.readStuff.unshift());
  }
  // If we want more, wait until we get more
  if (!areWeDone)
    client.on('custom_payload', function bleh(data) {
       // When push returns false, we should stop reading until _read is called again.
      if (!this.push(this.readStuff.unshift()))
        client.removeEventListener('custom_payload', bleh);
    });
};

readable.readStuff = [];
client.on('custom_payload', function(data) {
  if (data.channel === "stuff")
    readable.readStuff.push(data);
});
```

**Comment by deathcap** [comment]
Thanks, will add

**Comment by deathcap** [comment]
Hmm, maybe it would be cleaner if the parsed protocol data was available as a Stream as well, (as opposed an event emitter)? 

This would avoid the need for the plugin channel API to translate event emitter to stream (which could also probably be done with https://github.com/substack/emit-stream).

And then the plugin channel code could simply read the parsed packet stream, and [divert](https://github.com/voxel/voxel-clientmc/blob/master/mf-worker.js#L15-L30) custom_payload to its own per-channel streams.

**Comment by rom1504** [comment]
It is available in client.deserializer I think. (But that stream is changed
when the state changed so you need to redo your piping when it changes,
maybe we could wrap this into a single stream so people can just pipe it
without worrying about it changing)

**Comment by deathcap** [comment]
Closing this for now, I think a plugin channel API could be interesting but would need to nail down the use cases and API, maybe have a 'packet stream' for parsed packets available first, wrapping client.deserializer. Sort of like the other end of https://github.com/PrismarineJS/node-minecraft-protocol/pull/320 (streams in, and streams out)

**Pull request closed without merging**
