### PR TITLE
Fix proxy example not working for servers running in offline mode

### PR DESCRIPTION
**Pull request by IceTank**
Some yggdrasil authentication attempt somehow fails when trying to connect to an offline server making the proxy fail to connect.

### CODE REVIEW

**Comment by rom1504** [comment]
that's a much larger issue in mineflayer

we should make it much more explicit whether offline or online mode is used

**Comment by IceTank** [comment]
>we should make it much more explicit whether offline or online mode is used

So make the example ask for credentials instead? And then try to connect as an online or offline client?

**Comment by rom1504** [comment]
No, what I meant is this shows an issue in createClient
As this PR shows it is now confusing to know whether offline mode will be used or not
I think we should improve the doc on the topic or improve the API itself

**Comment by rom1504** [comment]
this is not needed now, issue fixed in nmp

**Pull request closed without merging**
