### PR TITLE
update to babel6

### PR DESCRIPTION
**Pull request by rom1504**
idk if we still need babel-runtime as a normal dep, needs testing.

### CODE REVIEW

**Comment by roblabla** [comment]
Let's wait for babel6 to become more stable. Right now some basic features are bug-riddled, and there are regressions here and there.

**Comment by rom1504** [comment]
ok

**Comment by rom1504** [comment]
@roblabla I think we could move to babel6 now, what do you think ? Some of the regressions I know of have been fixed.

**Comment by rom1504** [comment]
Well I can't see any remaining problem with babel6, let's move to it.

**Pull request merged**
