### PR TITLE
build(deps): bump prismarine-realms from 1.2.0 to 1.3.0

### PR DESCRIPTION
**Pull request by jojomatik**

### CODE REVIEW

**Comment by rom1504** [comment]
Why

**Comment by jojomatik** [comment]
prismarine-realms 1.3.0 includes a fix of the types that prevents (at least some) typescript projects using minecraft-protocol to properly build:

See: https://github.com/jojomatik/blockcluster/commit/9a8ada08e400f899a5309a23810d66508cea3a0e / https://github.com/jojomatik/blockcluster/actions/runs/3933361815/jobs/6726981849

**Comment by LucienHH** [comment]
There's no need to alter the package.json, the caret tells npm to install the latest minor/patch version.

**Comment by jojomatik** [comment]
> There's no need to alter the package.json, the caret tells npm to install the latest minor/patch version.

I see your point, after reverting and installing the latest version of `minecraft-protocol` I receive the new version of `prismarine-auth` in my `package-lock.json`. Didn't think about that. Thank you!

Doesn't update automatically though as version 1.2.0 is sufficient, which is why I usually upgrade dependency versions in my libraries.

Feel free to close the PR if you don't agree!

**Comment by LucienHH** [comment]
You can do `npm update --depth 9999` to update packages

**Comment by jojomatik** [comment]
> You can do `npm update --depth 9999` to update packages

Yes, but I usually use dependabot for dependency updates and it won't pick up anything deeper than 1 level, if not required by another package in depth 1. That's the reason why I personally believe updating it in a library is the better choice. But that's more of a philosophical question and not a situation where either of the approaches are objectively right or wrong.

**Comment by rom1504** [comment]
Package-lock locks dependencies so this PR won't impact anything there either

I advise to simply not use package-lock

**Comment by jojomatik** [comment]
> I advise to simply not use package-lock

That's a valid choice (especially for libraries).

If you want to, take a look into this article on the renovate docs: https://docs.renovatebot.com/dependency-pinning/

They discuss pros and cons of the different approaches in depth, which is how I formed my opinion on this topic.

**Pull request closed without merging**
