### PR TITLE
Improve badges

### PR DESCRIPTION
**Pull request by wtfaremyinitials**
The inconsistency was bothering me.

### CODE REVIEW

**Comment by roblabla** [comment]
Haha, thanks :D

**Comment by rom1504** [comment]
Well trouble is, that seems broken (both the npm and circle ci ones)

**Comment by wtfaremyinitials** [comment]
@rom1504 The npm one looks right to me. I did just notice however that the CI one is set to display the last build, not the last one on master. My bad PR is making the badge display a failure.

**Comment by rom1504** [comment]
yeah the npm one is ok, it's just weird that it is orange when usually it is green (see https://github.com/andrewrk/mineflayer for example)

**Pull request merged**
