### PR TITLE
Add snapshot `21w07a` support

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/21w07a/protocol.json#L1944 needs fixing

**Comment by rom1504** [comment]
can you add the version in the readme?

**Comment by u9g** [comment]
added

**Comment by rom1504** [comment]
tests still failing, looks like unlock_recipes is wrong

**Comment by rom1504** [comment]
probably would be easier to debug by running the tests locally

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
