### PR TITLE
Add support for non-full packets

### PR DESCRIPTION
**Pull request by Pandapip1**
CC #811, #1094

Currently, this project seems extraordinarily dead, in that it isn't being updated.

Admittedly, this PR is a band-aid and not a fix. But I'd rather have the option for hacky non-0% support than forced 0% support, when it comes to any recent version of the game.

### CODE REVIEW

**Comment by extremeheat** [comment]
What does this actually do?

**Comment by Pandapip1** [comment]
> What does this actually do?

It adds a client / server option to have `createDeserializer` return a `Parser` object instead of a `FullPacketParser`.

**Comment by extremeheat** [comment]
What does that do?

**Comment by Pandapip1** [comment]
> What does that do?

`FullPacketParser` performs packet validity checks. New minecraft versions extend the existing protocol in ways that break those validitity checks, but where existing code can read 90% of the useful information. `node-minecraft-protocol` does need to be updated to read that remaining 10% that gets cut off, *but that doesn't have to break compatibility if those features aren't yet needed.*

**Comment by extremeheat** [comment]
> extend the existing protocol in ways that break those validitity checks

Where in the code are you seeing this and for what version? Do you have a link to code somewhere?

**Comment by Pandapip1** [comment]
This conversation is already well-documented at #811, except oddly I can't find MC version numbers. IIRC, >1.9.0

https://github.com/ProtoDef-io/node-protodef/blob/e008e688d52478d82926888a59d85d79704ff462/src/serializer.js#L76

**Comment by extremeheat** [comment]
There is no such thing AFAIK of a partial packet. #811 is unrelated, that's caused by error in minecraft-data protocol, or invalid server data.

**Comment by Pandapip1** [comment]
> There is no such thing AFAIK of a partial packet. https://github.com/PrismarineJS/node-minecraft-protocol/issues/811 is unrelated, that's caused by error in minecraft-data protocol, or invalid server data.

Well then, this allows clients to handle invalid server data, and vice versa.

I'll fully admit: I'm not particularly experienced with regards to the MC protocol or protobuf in general. But what I do know is that there was a server that vanilla MC clients were able to connect to and that node-minecraft-protocol (and by extension, mineflayer) clients were not able to connect to.

**Comment by extremeheat** [comment]
I think you misunderstood my last comment. This PR implies there is a thing as a partial packet, like one that has variable length. Or something to do with packet batching. As far as I am aware, this does not exist. Actually I think this seems like a dupe PR of https://github.com/PrismarineJS/node-minecraft-protocol/pull/1094, what's changed here ?

As for #811, you are looking at two different errors. The deserializer (in node-minecraft-protocol) is failing to read something (not fatal) _and_ the serializer is encoding something that is being sent to a vanilla client, causing it to crash (which is fatal). These are two independent errors, and like I mention, caused by legitimate error in data from outside or a wrong definition in minecraft-data

**Comment by Pandapip1** [comment]
> I think you misunderstood my last comment. This PR implies there is a thing as a partial packet, like one that has variable length. Or something to do with packet batching. As far as I am aware, this does not exist. Actually I think this seems like a dupe PR of https://github.com/PrismarineJS/node-minecraft-protocol/pull/1094, what's changed here ?

#1094 and this PR share a git branch, which is why their files are synced. #1094 was closed when https://github.com/PrismarineJS/node-minecraft-protocol/pull/1278/commits/7da26b49285179e7277ca7911706da3e40d05b84 was the latest commit. It fully disabled the `FullPacketParser` all the time.

This PR adds an option to disable them instead of having it disabled 100% of the time.

**Comment by Pandapip1** [comment]
Never mind. I can't find the code that reproduces the error. Closing unless I can repro again.

**Comment by extremeheat** [comment]
Those errors are caused by bad definitions, missing definitions, or illegal packets being sent by the server. This PR wanted to just remove sanity checks which is not good (does not fix anything)

**Comment by Pandapip1** [comment]
> This PR wanted to just remove sanity checks which is not good (does not fix anything)

Correction: this PR added an option that would manually disable the sanity checks for debugging purposes.

**Comment by rom1504** [comment]
The current code https://github.com/Pandapip1/node-minecraft-protocol/blob/master/src/transforms/serializer.js#L5 is always using FullPacketParser and hence always parses partial packets if possible 

So the only only thing this PR would have done is add an option to *not* parse partial packets and instead crash.

**Pull request closed without merging**
