### PR TITLE
make 1.16.2 the tested version instead of 1.16.1

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
I'm betting on something wrong in https://github.com/ProtoDef-io/node-protodef/blob/master/src/datatypes/compiler-utils.js#L37
maybe you could have a quick look @Karang to see if you see anything obvious ? 
Problematic bitfield is there https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.2/protocol.json#L1587

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/718 could help simplify this procedure and confidence in it

**Comment by Karang** [comment]
> I'm betting on something wrong in https://github.com/ProtoDef-io/node-protodef/blob/master/src/datatypes/compiler-utils.js#L37
> maybe you could have a quick look @Karang to see if you see anything obvious ?
> Problematic bitfield is there https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.16.2/protocol.json#L1587

Nothing obvious, I'll run the test manually later.

**Comment by Karang** [comment]
Looks like the problem is in the generated test packet (p1), it doesn't match the schema (x, y, z gets generated inside and outside the bitfield):
```
p1: {
  "x": 1,
  "z": 1,
  "y": 1,
  "chunkCoordinates": {
    "x": 1,
    "z": 1,
    "y": 1
  },
  "notTrustEdges": true,
  "records": [
    1
  ]
}
p2: {
  "chunkCoordinates": {
    "x": 1,
    "z": 1,
    "y": 1
  },
  "notTrustEdges": true,
  "records": [
    1
  ]
}

1) packets 1.16.2
       play,ClientBound,packet_multi_block_change:

      Uncaught AssertionError [ERR_ASSERTION]: field x missing in p2, in p1 it has value 1
```

**Comment by rom1504** [comment]
I don't remember, I just removed this line.
These packets tests should be generalized and cleaned up I think https://github.com/ProtoDef-io/node-protodef/issues/83

**Comment by rom1504** [comment]
mc-server 1.16.2 "clients can log in and chat" failing now apparently

**Comment by rom1504** [comment]
most likely related to packet changes, I'll list them here so it's easier to update mineflayer and flying squid too

**Comment by rom1504** [comment]
reference https://github.com/PrismarineJS/minecraft-data/pull/326

**Comment by rom1504** [comment]
worked a bit on this. Main thing that is annoying is that login packet. The server is now expected to provide a big list of stuff each biome should be doing.
In 1.16.1 they introduced having to send a dimension codec which was already big, but now it's really way too big to put in the example.
I think we should save the default value in a json in minecraft-data. and then it would be used here and in flying-squid in one line.
Will do that another time

**Comment by GroobleDierne** [comment]
> 
> 
> worked a bit on this. Main thing that is annoying is that login packet. The server is now expected to provide a big list of stuff each biome should be doing.
> In 1.16.1 they introduced having to send a dimension codec which was already big, but now it's really way too big to put in the example.
> I think we should save the default value in a json in minecraft-data. and then it would be used here and in flying-squid in one line.
> Will do that another time

When you say `I think we should save the default value in a json in minecraft-data`, are you talking about the whole login packet or just the dimension codec field ?

**Comment by rom1504** [comment]
yes
in the previous versions it was reasonable to store this directly in the example as it was only tens of lines, now it's thousands of lines, it's not reasonable anymore, which is why I'm suggesting to put it in mc data

**Comment by GroobleDierne** [comment]
I am interested to do it, is there an existing file for these data?

**Comment by rom1504** [comment]
no but

> As mentioned in the Discord server, the approach to generating this data would be to log into a 1.16.2 server using mc-protocol and basically save all data from the login packet. Then simply extract the biome data elements into MC-Data.

**Comment by GroobleDierne** [comment]
I meant in MCData

**Comment by rom1504** [comment]
same answer

**Comment by GroobleDierne** [comment]
ok

**Comment by rom1504** [comment]
@GroobleDierne released your file as mc data 2.69.0, you can now use it as .loginPacket here

**Comment by GroobleDierne** [comment]
Thanks. I will do a PR soon for NMP

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/pull/765

**Comment by rom1504** [comment]
closing in favor of #765

**Pull request closed without merging**
