### PR TITLE
Update version.js to support 1.20.6

### PR DESCRIPTION
**Pull request by TrevorJTClarke**

### CODE REVIEW

**Comment by extremeheat** [comment]
1.20.6 is not supported by node-minecraft-protocol or minecraft-protocol. If you are interested the first step would be to update the protocol definitions in minecraft-data.

**Comment by Emibergo02** [comment]
How?

**Comment by extremeheat** [comment]
You can join the discord (link in readme) and join the #contribute room if you want to discuss

First step would be to update minecraft-data protocol by looking through changes in wiki.vg and the changes made to the decompiled minecraft source code from old to new version.

**Comment by Faaiq-84** [comment]
Well can i join to search it?

**Pull request closed without merging**
