### PR TITLE
1.7 support

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
@deathcap it seems it's failing in auth. I bet you only tested it in offline mode too ?

**Comment by rom1504** [comment]
`/home/ubuntu/node-minecraft-protocol/node_modules/source-map-support/source-map-support.js:407` wtf why do I still get that error even though I disabled source-map-support in the tests

**Comment by rom1504** [comment]
```
1) client 1.7.10 connects successfully - online mode:
     Uncaught Error: Not a public key.
      at Object.createPublicKey (node_modules/ursa-purejs/lib/ursa.js:370:19)
      at mcPubKeyToURsa (dist/client/encrypt.js:66:15)
      at sendEncryptionKeyResponse (dist/client/encrypt.js:44:22)
      at onJoinServerResponse (dist/client/encrypt.js:35:11)
      at node_modules/yggdrasil/lib/index.js:207:7
      at Request._callback (node_modules/yggdrasil/lib/index.js:144:9)
      at Request.self.callback (node_modules/yggdrasil/node_modules/request/request.js:121:22)
      at Request.<anonymous> (node_modules/yggdrasil/node_modules/request/request.js:978:14)
      at IncomingMessage.<anonymous> (node_modules/yggdrasil/node_modules/request/request.js:929:12)
      at endReadableNT (_stream_readable.js:905:12)
```

**Comment by deathcap** [comment]
Hmm, I did test only offline but testing online now I'm not able to replicate this error, at least testing with the `client_auto` example connecting to a 1.7.10 server:

```
MC-PROTO: 92597 pinging localhost
MC-PROTO: 92597 writing packet handshaking.set_protocol
MC-PROTO: 92597 { protocolVersion: 47,
  serverHost: 'localhost',
  serverPort: 17100,
  nextState: 1 }
MC-PROTO: 92597 writing packet status.ping_start
MC-PROTO: 92597 {}
MC-PROTO: 92597 read packet status.server_info
MC-PROTO: 92597 { response: '{"description":"A Minecraft Server","players":{"max":20,"online":0},"version":{"name":"1.7.10","protocol":5}}' }
MC-PROTO: 92597 writing packet status.ping
MC-PROTO: 92597 { time: [ 0, 0 ] }
MC-PROTO: 92597 read packet status.ping
MC-PROTO: 92597 { time: [ 0, 0 ] }
MC-PROTO: 92597 ping response { description: 'A Minecraft Server',
  players: { max: 20, online: 0 },
  version: { name: '1.7.10', protocol: 5 },
  latency: 2 }
MC-PROTO: 92597 Server description: A Minecraft Server
MC-PROTO: 92597 Server version: 1.7.10, protocol: 5
connected
```

but it never finishes logging in. Doesn't seem related to https://github.com/PrismarineJS/node-minecraft-protocol/issues/358 (occurs with both protodef 0.2.5 and 0.3.0).

**Comment by rom1504** [comment]
Maybe we should use the parallel build feature of circle ci, seeing how slow this is getting.

**Comment by rom1504** [comment]
@deathcap alright, I fixed the other problems, now you should be able to reproduce the public key error

**Comment by deathcap** [comment]
@rom1504 Found the problem (varint -> short in handshake packets) but I see you beat me to it =) https://github.com/PrismarineJS/minecraft-data/commit/62169cdc51f9723613e4eda095e5987baa4a5a8f - works now for me too

**Pull request merged**
