### PR TITLE
[WIP] Modularize NMP

### PR DESCRIPTION
**Pull request by roblabla**
This is a first, crude attempt at modularizing NMP, mostly meant to ignite some discussion. I chose to modularize the keepalive module as it is fairly simple and straightforward. I plan on modularizing two other components before calling this feature-complete : 
- [ ] Handshaking
- [x] Ping

Open questions : 
- Should we provide a way to detach a module from NMP ?
- Should we actually standardize modules, or should they be kept internal ?

### CODE REVIEW

**Comment by rom1504** [comment]
Nice ! createServer is much better that way, only thing remaining is a handshaking module ?

And the same thing for createClient :)

**Comment by rom1504** [comment]
might want to rebase this on master so it either passes the test, either tell us what went wrong.

**Comment by roblabla** [comment]
Going to rewrite this, too many changes happened since this was written, the merge conflicts are hard as fuck to resolve.

**Comment by deathcap** [comment]
Some notes on modularization:

Goals: better support new use cases, e.g websockets, Forge, cross-version, auto-negotiation, browser, and future unexpected usage

Logical components (basic building blocks):

* [x] Data/protocol specifications: minecraft-data, node-minecraft-data
* [x] Compressor: src/transforms/compression.js, zlib deflate, threshold
* [x] Framer: src/transforms/framing.js - note: ws disable
* [x] Serializer: src/transforms/serializer.js packet stream
* [ ] Keep-alive: respond to keep-alive packets for server (in this PR)
* [ ] Ping: responds to ping in the server (in this PR)
 * [ ] FE01 ping https://github.com/PrismarineJS/node-minecraft-protocol/issues/332
* [ ] Login: handle client logins in the server (in this PR), onEncryptionKeyResponse, loginClient, ursa..
* [ ] Login/handshake client: onEncryptionKeyResponse, yggdrasil, ...
* [ ] `set_protocol` client: version, host (changed by FML), port, next state 2
 * [ ] Client ping: also uses `set_protocol` but different next state 1
* [ ] `FML|HS` handshake (nmp-forge): change host, handshake on plugin channels
* [ ] Plugin channels: streams, registration, https://github.com/PrismarineJS/node-minecraft-protocol/pull/328
* [ ] DNS SRV resolution (createClient connect)
* [ ] TCP sockets (`net`): usual final endpoint to the stream

Advanced usage (compose from above and other components):

* [ ] Cross-version dynamic https://github.com/PrismarineJS/node-minecraft-protocol/issues/234 (nmp-auto) = client ping (FE01?) +`set_protocol` + `FML|HS`
* [ ] Websocket-compatible = data + compressor + serializer + keepalive; without: framer, TCP, login/handshake. https://github.com/PrismarineJS/node-minecraft-protocol/pull/320 Client stream / wsmc
* [ ] Browser = websocket-compatible + `websocket-stream`/`worker-stream` (3rd party modules)
* [ ] Web-based Minecraft client = browser + mineflayer + voxel.js (etc.)
* [ ] Proxy = ...

**Comment by rom1504** [comment]
would be nice to get this over with

**Pull request closed without merging**
