### PR TITLE
add dts for better autocomplete suggestion

### PR DESCRIPTION
**Pull request by bangbang93**
add dts for better autocomplete suggestion
image

No js code change, so should not have any side effects

### CODE REVIEW

**Comment by rom1504** [comment]
Looks good. Do you know if most ide handle this ?

**Comment by rom1504** [comment]
And could we have some tool checking that the type definition and the code match ? (Otherwise I'm afraid it'll be out of sync soon)

**Comment by bangbang93** [comment]
Both VS Code and Webstorm supports typescript definition by default. The others I have not use them so I'm not sure.
The definition cannot be auto generated when js code was changed.
Definition test can use the typescript compiler. But it only checks type definition, not the underlying js object.
This can only be manually updated unless the project is written in typescript.

**Comment by rom1504** [comment]
thanks, merged !

**Comment by ShayBox** [comment]
Finally typings 😄 Now you can use them to generate docs, and as long as they're kept up to date when changes are made you can have good updated docs

**Comment by ShayBox** [comment]
Thought it would be great if you could not use the any type, and make the typings using strict mode, so they're actually usable for anything but auto completion.

**Comment by jwulf** [comment]
The best way to ensure typings do not drift from the code is to convert the code to TypeScript.

**Pull request merged**
