### PR TITLE
Handle signed commands in 1.19.0 and 1.19.2

### PR DESCRIPTION
**Pull request by extremeheat**
* Fixes commands that require message signing (/me, /kick, /ban, etc.). For commands with complex serialization this may break due  to handling spaces, but for now makes all the vanilla commands that need signing work.
* fixes field naming issue with chat header handling
* update types
* after https://github.com/PrismarineJS/minecraft-data/pull/671

### CODE REVIEW

**Comment by rom1504** [comment]
Is this ready?

**Comment by extremeheat** [comment]
Should be mergeable, yeah.

**Comment by rom1504** [comment]
Can you rebase on master ?

**Review by DarkCoder15 — APPROVED** [review]
lgtm

**Comment by rom1504** [comment]
@extremeheat can you rebase please ?

**Comment by extremeheat** [comment]
Fixed the conflicts, since there are some big changes with the 1.19.3 implementation here that I haven't looked into I updated the PR to reflect that this only works on 1.19.0/1.19.1/1.19.2

**Pull request merged**
