### PR TITLE
Packets 1.8

### PR DESCRIPTION
**Pull request by roblabla**
1.8 support in here !

What needs to be done : 

- Client has been entirely untested right now.
- Server is somewhat tested, I know that server_helloworld.js works. 
- Need to check if unit tests pass
- And obviously, need to add acknowledgements in the README : big thanks to @wtfaremyinitials

### CODE REVIEW

**Comment by roblabla** [comment]
I'll go through the things for the PR to be complete tomorrow (checking the unit tests and examples, and finishing the readme). If everything works flawlessly, I'll pull the PR and create a new version on NPM

**Comment by wtfaremyinitials** [comment]
Awesome

**Comment by wtfaremyinitials** [comment]
It seems that the client side is completely broken. From what I've gathered, it looks like it never transitions from the `login` state to the `play` state. Where is this supposed to happen? (@roblabla)

**Comment by roblabla** [comment]
https://github.com/andrewrk/node-minecraft-protocol/blob/master/index.js#L336 there ?

**Comment by wtfaremyinitials** [comment]
```js
var mc = require('../')
  , states = mc.protocol.states

var client = mc.createClient({
  username: 'Player'
});
client.on('connect', function() {
  console.info('connected');
  console.log(client.state);
});
```

```bash
$ node examples/client_echo.js 
connected
login
```

**Comment by roblabla** [comment]
That's half-normal. The "connect" event is emitted when the client actually completes a connection with the server, before any packets is sent.  What you should do is listen for the 'state' event, which is emitted each time there is a state change. That should give you more conclusive evidence. Also, you should run the client with ```NODE_DEBUG=mc-proto node examples/client_echo.js```. This will give you a lot of useful information about which packets are read and written.

**Comment by wtfaremyinitials** [comment]
```bash
$ NODE_DEBUG=mc-proto node examples/client_echo.js 
MC-PROTO: 43473 Old-styling packet
MC-PROTO: 43473 writing packetId handshaking.set_protocol (0x0)
MC-PROTO: 43473 { protocolVersion: 47,
  serverHost: 'localhost',
  serverPort: 25565,
  nextState: 2 }
MC-PROTO: 43473 <Buffer 0f 00 2f 09 6c 6f 63 61 6c 68 6f 73 74 63 dd 02>
login
MC-PROTO: 43473 Old-styling packet
MC-PROTO: 43473 writing packetId login.login_start (0x0)
MC-PROTO: 43473 { username: 'Player' }
MC-PROTO: 43473 <Buffer 08 00 06 50 6c 61 79 65 72>
MC-PROTO: 43473 read packetId login.compress (0x3)
MC-PROTO: 43473 { id: 3, threshold: 256 }
```

node cleanly exits after reading the 0x03 login compression packet.

**Comment by wtfaremyinitials** [comment]
Just confirmed, onLogin never gets called.

**Comment by wtfaremyinitials** [comment]
Just confirmed, onLogin never gets called.

**Comment by wtfaremyinitials** [comment]
Looks like reading compressed packets never got implemented, so everything after 0x03 (set compression) gets dropped. Since 0x02 (login) is sent *after* 0x03, the login is never received.

**Comment by wtfaremyinitials** [comment]
I guess parsePacket needs to become async, unless we find a lib that has sync zlib.

**Comment by roblabla** [comment]
@wtfaremyinitials We shouldn't try to make it sync if it involves IO. Making it async shouldn't be too much work anyway.

**Comment by wtfaremyinitials** [comment]
@roblabla The parse function is in a `while` loop, so making it work asynchronously will break almost everything. I agree though, we should try to make it async.

**Comment by wtfaremyinitials** [comment]
My async parseNewStylePacket is pushed to [packets-1.8](https://github.com/wtfaremyinitials/node-minecraft-protocol/tree/packets-1.8). I have to go right now, but you're welcome to finish that off.

**Comment by roblabla** [comment]
Doesn't really matter too much that it's in a while loop, all we need to do is make the function call itself again in the callback until we meet a terminal condition, effectively turning the whole thing recursive.

**Comment by wtfaremyinitials** [comment]
I just finished turning the whole thing recursive, but it seems to not work properly. The client connects, doesn't fire any chat events, then cleanly exits after about 10 seconds. ([packets-1.8](https://github.com/wtfaremyinitials/node-minecraft-protocol/tree/packets-1.8))

**Comment by wtfaremyinitials** [comment]
Did you ever figure this out? @roblabla

**Comment by roblabla** [comment]
Well, I'm almost done, but the damn thing is entering an infinite recursion and leaking memory until it ooms my machine. Then stuff happened and I sorta never found the time to do this. I'll take a look right now.

**Comment by roblabla** [comment]
OK, so either nodejs has a bug, or I'm going crazy. The code : 
```javascript
   var dataLengthField = readVarInt(buffer, cursor);
   cursor += dataLengthField.size;
   console.log("Got here");
   if(dataLengthField.value != 0) {
     zlib.inflateRaw(buffer.slice(cursor, cursor + dataLengthField.value), function(err, buffer) {
       if (err) console.log(err);
       else console.log("Got a packet v2");
       cursor = 0;
       finishParsing(buffer);
     });
   } else {
     console.log("Got a packet v1");
     finishParsing(buffer);
   }
```

This code prints "Got Here", but never prints anything else... No error, nothing...

**Comment by roblabla** [comment]
Well I debugged that one. Now, for some reason, ```crypto.randomBytes``` never calls my callback. I'm going from hurdle to hurdle here.

**Comment by wtfaremyinitials** [comment]
Huh that's odd. Can you push a version to roblabla/node-minecraft-protocol that has this issue? I'd be happy to look at it.

**Comment by roblabla** [comment]
@wtfaremyinitials Done. looking at the results of the top command, it looks like the code enters an infinite loop or something, cpu goes to 100%... I don't have any debuggers though, so it's rough debugging that.

**Comment by roblabla** [comment]
After looking at my code long enough in a mean way, I found the culprit for this bug. Now we've got... another bug. Pushing new code.

**Comment by roblabla** [comment]
I never seem to read the Login packet the server is supposed to send me now. I'm debugging using the ``example/client_chat.js``. I'm giving up for now, I need to take a break.

**Comment by JavaPortals** [comment]
What bug did you find?

**Comment by roblabla** [comment]
@JavaPortals Somehow, the login packet the server sends is never read, no idea why. Could be an infinite loop, or any other kind of bugs. I need to setup myself a proper debugging environment (currently using io.js instead of node.js, which is incompatible with most debuggers out there...). If you find something, please do tell me :D

**Comment by JavaPortals** [comment]
I'll see what I can do

**Comment by roblabla** [comment]
Should now be working, for the most part. I'll write a quick-n-dirty proxy and use it to test out all the packets in practice.

**Comment by roblabla** [comment]
This should make the protocol 100% complete. Only tests are missing, then I'll squash the commits so only one remains.

**Comment by roblabla** [comment]
Should be ready to merge.

**Comment by wtfaremyinitials** [comment]
```js
will@arya node-minecraft-protocol(review-108) $ node examples/proxy.js 

/Users/will/Projects/node-minecraft-protocol/examples/proxy.js:85
      console.log(`client<-server: Error in packetId ${state}.0x${packetId.val
                  ^
SyntaxError: Unexpected token ILLEGAL
```

**Comment by wtfaremyinitials** [comment]
```js
will@arya node-minecraft-protocol(review-108) $ mocha
Beginning write test
Finished write test in 4.145 seconds

buffer.js:784
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeInt8 (buffer.js:892:5)
    at Array.writeByte [as 1] (/Users/will/Projects/node-minecraft-protocol/lib/protocol.js:1190:10)
    at write (/Users/will/Projects/node-minecraft-protocol/lib/protocol.js:1430:17)
    at /Users/will/Projects/node-minecraft-protocol/lib/protocol.js:1489:14
    at Array.forEach (native)
    at createPacketBuffer (/Users/will/Projects/node-minecraft-protocol/lib/protocol.js:1484:10)
    at Client.write (/Users/will/Projects/node-minecraft-protocol/lib/client.js:199:16)
    at Object.<anonymous> (/Users/will/Projects/node-minecraft-protocol/test/benchmark.js:49:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by wtfaremyinitials** [comment]
Woot :smile:

**Pull request merged**
