### PR TITLE
use esnext to get more es6, mostly require/module.exports -> import/export

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
For reference:
1. `npm install -g esnext`
2. `for i in `find src -name "*.js"` ; do esnext -I "$i"; done`
3.  fix stuff it broke

**Comment by roblabla** [comment]
I'm not a big fan of the es6 import/export syntax personally. The fact that es6 has different "types" of export (export default and the rest) pisses me off greatly.

IMO, the require function/module.exports variable are much clearer. Besides they're unlikely to be unsupported in the future.

Just my 2c.

**Comment by rom1504** [comment]
Yeah I agree import/export don't improve the code much. This was more an experiment that something I really care to change.

I'll try running telling esnext to not change the require, see if some improvements can be done anyway.

**Comment by rom1504** [comment]
The good point about import/export is it makes static analysis a bit easier. But yeah not sure if it's worth it.

**Comment by rom1504** [comment]
Looking at babel code ATM and they have really clean code. They use import/export which actually look pretty good. They also use flow which is pretty useful. I'm going to try and see if any of this can apply here.

**Comment by rom1504** [comment]
Let's not merge this.

**Pull request closed without merging**
