### PR TITLE
Update package.json to indirect request dependency

### PR DESCRIPTION
**Pull request by bdsomer**

### CODE REVIEW

**Comment by plexigras** [comment]
this change is already implemented

**Comment by rom1504** [comment]
Yggdrasil is broken due to your change @bdsomer

See https://github.com/zekesonxx/node-yggdrasil/issues/24

Please fix it

We will update to Yggdrasil 1.1.0 when it's fixed.

**Comment by bdsomer** [comment]
@rom1504 Uh oh, sorry about that :\

Should be fixed by the end of tomorrow

**Comment by bdsomer** [comment]
@rom1504 could you reopen and merge now? I fixed the issue.

**Comment by bdsomer** [comment]
@rom1504 ah, I see, you merged the Greenkeeper PR. Awesome!

**Pull request closed without merging**
